version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongodb:/mongodb
  expressapp:
    build: .
    ports:
      - "3000:3000"
